### ISSUE TITLE
Failed to run cfn-init

### ISSUE THREAD

**Issue by ccummings1** [splunk/splunk-aws-cloudformation#9] opened 2015-05-20 23:47 UTC
I see the below issue when trying to run a small deployment

6:45:26 UTC-0700	CREATE_FAILED	AWS::CloudFormation::Stack	Master-BastionHost-KBPI1BOJYH7P	The following resource(s) failed to create: [ControllerCondition].
16:45:25 UTC-0700	CREATE_FAILED	AWS::CloudFormation::WaitCondition	ControllerCondition	WaitCondition received failed message: 'Failed to run cfn-init' for uniqueId: i-94dc6a56

**Comment by rarsan** [comment] 2015-07-13 05:27
@ccummings1 thanks for reporting this. Is this still occuring?
If so, can you please paste contents of **/var/log/cloud-init.log** and **/var/log/cfn-init.log** from the corresponding ec2 instance.

**Comment by rarsan** [comment] 2015-07-14 00:35
I think I managed to repro this issue. Can't be certain it's the same without your logs, but it's likely the same root cause: I traced it to a bug in aws cfn-init which strangely fails to install a required package (python-boto). Pushed a workaround (c92fe596fbf512da341b01909d1a1f2cae837f78 ) where we manually install the package instead.

**Comment by rarsan** [comment] 2015-07-15 23:34
Closing. Please re-open if this is still occurring.

**Closed by rarsan** 2015-07-15 23:34 UTC
Labels: bug
